name: profair
description: A project have change the life people.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^5.4.4
  dio: ^5.0.0
  flutter_modular: ^5.0.3
  skeletons: ^0.0.3
  share_plus: ^6.3.1
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^10.4.3
  http: ^0.13.6
  shared_preferences: ^2.2.0
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  provider: ^6.0.5
  fl_chart: ^0.62.0
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  appwrite: ^9.0.0
  flutter_svg: ^2.0.7
  auto_route: ^7.8.1
  animated_flip_counter: ^0.2.6
  csv: ^5.0.2
  file_picker: ^5.2.10
  url_launcher: ^6.1.14
  qr_flutter: ^4.1.0
  printing: ^5.11.0
  pdf: ^3.10.4

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Medium.ttf
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-Light.ttf
        - asset: fonts/inter/Inter-Bold.ttf
    - family: Sf
      fonts:
        - asset: fonts/sf/SF-Bold.otf
        - asset: fonts/sf/SF-Light.otf
        - asset: fonts/sf/SF-Medium.otf
        - asset: fonts/sf/SF-Medium-Italic.eot
        - asset: fonts/sf/SF-Bold-Italic.eot
        - asset: fonts/sf/SF-Light-Italic.eot

  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
